apiVersion: v1
kind: Secret
metadata:
  name: mn-tls
  namespace: parity-mn
data:
  tls.crt: ./secret/mn-bundle.crt
  tls.key: ./secret/mn-key.key

# Note: this may need to be run from the command line
# $ kubectl create secret tls mn-tls \
#   --key ./secret/mn-key.key \
#   --cert ./secret/mn-bundle.crt \
#   --namespace parity-mn