kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mainnet-ssd
  namespace: parity-mn
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zones: us-west1-a
reclaimPolicy: Retain