apiVersion: v1
kind: Service
metadata:
  name: parity-service
  namespace: parity-rp
  labels:
    app: parity-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 8545
    protocol: TCP
    name: rpc
  selector:
    app: parity-app