apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: parity-ingress
  namespace: parity-rp
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.org/ssl-services: parity-service
spec:
  tls:
  - secretName: tls-certificate
    hosts:
    - geth-ropsten.coinalpha.com
  rules:
  - host: geth-ropsten.coinalpha.com
    http:
      paths:
      - path: /
        backend:
          serviceName: parity-service
          servicePort: 8545